module.exports = [
  {
    id: 12,
    title: "Xiaomi Note 3",
    price: 679.99,
    description:
      "Tofu hoodie pop-up try-hard vice cornhole gluten-free keytar mlkshk 8-bit small batch four loko letterpress. Yr cornhole hoodie tote bag wayfarers mustache mumblecore crucifix hell of single-origin coffee pinterest. Readymade la croix activated charcoal cray edison bulb. Woke marfa helvetica hashtag green juice keffiyeh street art locavore four loko brunch flexitarian. Wayfarers fanny pack pork belly semiotics VHS affogato mixtape tumblr glossier jianbing freegan kinfolk pug. Intelligentsia pug 8-bit microdosing salvia locavore 90's umami gastropub iceland church-key marfa readymade 3 wolf moon keffiyeh. Tofu seitan mlkshk, try-hard cray hella PBR&B kale chips bushwick umami salvia knausgaard four loko pork belly semiotics.",
    featured: null,
    created_at: "2020-01-03T22:46:09.103Z",
    updated_at: "2020-01-03T22:46:09.103Z",
    category: "phone",
    free_shipping: null,
    extra_field: null,
    image: {
      id: 15,
      name: "product-5.png",
      hash: "69e25f8265d546089f1d289a3e0b505d",
      sha256: "dIVO5EOsxZZaPR2gc47VREZRnay8gPDbdb2tEHnHW_I",
      ext: ".png",
      mime: "image/png",
      size: "189.05",
      url:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1578091569/lt0jbm9hvmcvdurx9mdm.png",
      provider: "cloudinary",
      provider_metadata: {
        public_id: "lt0jbm9hvmcvdurx9mdm",
        resource_type: "image",
      },
      created_at: "2020-01-03T22:46:09.550Z",
      updated_at: "2020-01-03T22:46:09.550Z",
    },
  },
  {
    id: 8,
    title: "Pixel Phone",
    price: 300.99,
    description:
      "Tofu hoodie pop-up try-hard vice cornhole gluten-free keytar mlkshk 8-bit small batch four loko letterpress. Yr cornhole hoodie tote bag wayfarers mustache mumblecore crucifix hell of single-origin coffee pinterest. Readymade la croix activated charcoal cray edison bulb. Woke marfa helvetica hashtag green juice keffiyeh street art locavore four loko brunch flexitarian. Wayfarers fanny pack pork belly semiotics VHS affogato mixtape tumblr glossier jianbing freegan kinfolk pug. Intelligentsia pug 8-bit microdosing salvia locavore 90's umami gastropub iceland church-key marfa readymade 3 wolf moon keffiyeh. Tofu seitan mlkshk, try-hard cray hella PBR&B kale chips bushwick umami salvia knausgaard four loko pork belly semiotics.",
    featured: true,
    created_at: "2020-01-03T22:03:57.902Z",
    updated_at: "2020-01-03T22:03:57.902Z",
    category: "phone",
    free_shipping: true,
    extra_field: null,
    image: {
      id: 11,
      name: "product-1.png",
      hash: "4cabddb43dcd4e2e931ed75bde99bfdb",
      sha256: "zRfDSLWAQNVU4g1bPgfnsBx112PQEOeRCszfIqts-0U",
      ext: ".png",
      mime: "image/png",
      size: "271.07",
      url:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1578090865/qfdejom3jazv4aonc9ob.png",
      provider: "cloudinary",
      provider_metadata: {
        public_id: "qfdejom3jazv4aonc9ob",
        resource_type: "image",
      },
      created_at: "2020-01-03T22:34:25.992Z",
      updated_at: "2020-01-03T22:34:25.992Z",
    },
  },
  {
    id: 10,
    title: "Samsung Galaxy A8",
    price: 500.99,
    description:
      "Tofu hoodie pop-up try-hard vice cornhole gluten-free keytar mlkshk 8-bit small batch four loko letterpress. Yr cornhole hoodie tote bag wayfarers mustache mumblecore crucifix hell of single-origin coffee pinterest. Readymade la croix activated charcoal cray edison bulb. Woke marfa helvetica hashtag green juice keffiyeh street art locavore four loko brunch flexitarian. Wayfarers fanny pack pork belly semiotics VHS affogato mixtape tumblr glossier jianbing freegan kinfolk pug. Intelligentsia pug 8-bit microdosing salvia locavore 90's umami gastropub iceland church-key marfa readymade 3 wolf moon keffiyeh. Tofu seitan mlkshk, try-hard cray hella PBR&B kale chips bushwick umami salvia knausgaard four loko pork belly semiotics.",
    featured: null,
    created_at: "2020-01-03T22:27:00.581Z",
    updated_at: "2020-01-03T22:27:00.581Z",
    category: "phone",
    free_shipping: true,
    extra_field: null,
    image: {
      id: 12,
      name: "product-3.png",
      hash: "fb85ae5094f543e2a76045ed062b9979",
      sha256: "6_n7VV4NR+aIMGnk1RZ3B0v3uOtVgH+ydhmdVVfciPY",
      ext: ".png",
      mime: "image/png",
      size: "235.81",
      url:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1578090878/zffv0duvkcybliwryfuy.png",
      provider: "cloudinary",
      provider_metadata: {
        public_id: "zffv0duvkcybliwryfuy",
        resource_type: "image",
      },
      created_at: "2020-01-03T22:34:38.344Z",
      updated_at: "2020-01-03T22:34:38.344Z",
    },
  },
  {
    id: 9,
    title: "Windows Phone",
    price: 200.99,
    description:
      "Tofu hoodie pop-up try-hard vice cornhole gluten-free keytar mlkshk 8-bit small batch four loko letterpress. Yr cornhole hoodie tote bag wayfarers mustache mumblecore crucifix hell of single-origin coffee pinterest. Readymade la croix activated charcoal cray edison bulb. Woke marfa helvetica hashtag green juice keffiyeh street art locavore four loko brunch flexitarian. Wayfarers fanny pack pork belly semiotics VHS affogato mixtape tumblr glossier jianbing freegan kinfolk pug. Intelligentsia pug 8-bit microdosing salvia locavore 90's umami gastropub iceland church-key marfa readymade 3 wolf moon keffiyeh. Tofu seitan mlkshk, try-hard cray hella PBR&B kale chips bushwick umami salvia knausgaard four loko pork belly semiotics.",
    featured: null,
    created_at: "2020-01-03T22:24:37.253Z",
    updated_at: "2020-01-03T22:24:37.253Z",
    category: "phone",
    free_shipping: false,
    extra_field: null,
    image: {
      id: 13,
      name: "product-2.png",
      hash: "7980bfe4314141699f6a7eeb42e5c18c",
      sha256: "tdBduMxSfTFvUbZ-5svpcfHzNyTuGX9Z86m-PuLaIzY",
      ext: ".png",
      mime: "image/png",
      size: "317.35",
      url:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1578090896/kym4fp8lmm1ys8pqpenz.png",
      provider: "cloudinary",
      provider_metadata: {
        public_id: "kym4fp8lmm1ys8pqpenz",
        resource_type: "image",
      },
      created_at: "2020-01-03T22:34:57.036Z",
      updated_at: "2020-01-03T22:34:57.036Z",
    },
  },
  {
    id: 11,
    title: "Samsung S7",
    price: 750.99,
    description:
      "Tofu hoodie pop-up try-hard vice cornhole gluten-free keytar mlkshk 8-bit small batch four loko letterpress. Yr cornhole hoodie tote bag wayfarers mustache mumblecore crucifix hell of single-origin coffee pinterest. Readymade la croix activated charcoal cray edison bulb. Woke marfa helvetica hashtag green juice keffiyeh street art locavore four loko brunch flexitarian. Wayfarers fanny pack pork belly semiotics VHS affogato mixtape tumblr glossier jianbing freegan kinfolk pug. Intelligentsia pug 8-bit microdosing salvia locavore 90's umami gastropub iceland church-key marfa readymade 3 wolf moon keffiyeh. Tofu seitan mlkshk, try-hard cray hella PBR&B kale chips bushwick umami salvia knausgaard four loko pork belly semiotics.",
    featured: null,
    created_at: "2020-01-03T22:37:39.226Z",
    updated_at: "2020-01-03T22:37:39.226Z",
    category: "phone",
    free_shipping: true,
    extra_field: null,
    image: {
      id: 14,
      name: "product-4.png",
      hash: "9d6fc308cb9d4d7a8234010f04a85c88",
      sha256: "kUiGQ2XB2YU2yfB5byIw2jDr74x4J5OOzd4koNjiooc",
      ext: ".png",
      mime: "image/png",
      size: "155.89",
      url:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1578091059/yedjpkwxljtb75t3tezl.png",
      provider: "cloudinary",
      provider_metadata: {
        public_id: "yedjpkwxljtb75t3tezl",
        resource_type: "image",
      },
      created_at: "2020-01-03T22:37:39.679Z",
      updated_at: "2020-01-03T22:37:39.679Z",
    },
  },
  {
    id: 15,
    title: "Compaq ",
    price: 770.99,
    description:
      "Tofu hoodie pop-up try-hard vice cornhole gluten-free keytar mlkshk 8-bit small batch four loko letterpress. Yr cornhole hoodie tote bag wayfarers mustache mumblecore crucifix hell of single-origin coffee pinterest. Readymade la croix activated charcoal cray edison bulb. Woke marfa helvetica hashtag green juice keffiyeh street art locavore four loko brunch flexitarian. Wayfarers fanny pack pork belly semiotics VHS affogato mixtape tumblr glossier jianbing freegan kinfolk pug. Intelligentsia pug 8-bit microdosing salvia locavore 90's umami gastropub iceland church-key marfa readymade 3 wolf moon keffiyeh. Tofu seitan mlkshk, try-hard cray hella PBR&B kale chips bushwick umami salvia knausgaard four loko pork belly semiotics.",
    featured: null,
    created_at: "2020-01-03T22:54:14.320Z",
    updated_at: "2020-01-04T12:42:35.187Z",
    category: "computer",
    free_shipping: true,
    extra_field: null,
    image: {
      id: 18,
      name: "product-8.png",
      hash: "22d434fbd05442a1ad21595a7685b447",
      sha256: "-IUylHvR2SKyO4ApGvmFoBhCWhcVR-nH9tSeSjv6ieU",
      ext: ".png",
      mime: "image/png",
      size: "253.17",
      url:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1578092054/drfc8s0em4lvwnktaccw.png",
      provider: "cloudinary",
      provider_metadata: {
        public_id: "drfc8s0em4lvwnktaccw",
        resource_type: "image",
      },
      created_at: "2020-01-03T22:54:14.777Z",
      updated_at: "2020-01-03T22:54:14.777Z",
    },
  },
  {
    id: 14,
    title: " Zx Spectrum ",
    price: 640.99,
    description:
      "Tofu hoodie pop-up try-hard vice cornhole gluten-free keytar mlkshk 8-bit small batch four loko letterpress. Yr cornhole hoodie tote bag wayfarers mustache mumblecore crucifix hell of single-origin coffee pinterest. Readymade la croix activated charcoal cray edison bulb. Woke marfa helvetica hashtag green juice keffiyeh street art locavore four loko brunch flexitarian. Wayfarers fanny pack pork belly semiotics VHS affogato mixtape tumblr glossier jianbing freegan kinfolk pug. Intelligentsia pug 8-bit microdosing salvia locavore 90's umami gastropub iceland church-key marfa readymade 3 wolf moon keffiyeh. Tofu seitan mlkshk, try-hard cray hella PBR&B kale chips bushwick umami salvia knausgaard four loko pork belly semiotics.",
    featured: null,
    created_at: "2020-01-03T22:51:52.119Z",
    updated_at: "2020-01-04T12:43:10.389Z",
    category: "computer",
    free_shipping: true,
    extra_field: null,
    image: {
      id: 17,
      name: "product-7.png",
      hash: "65b6693f671746c0a55511e6ae45c0bc",
      sha256: "btme0HsPwhPWKi-JN-Ka-YgJASS4iymtPFnXblfBlao",
      ext: ".png",
      mime: "image/png",
      size: "284.82",
      url:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1578091912/teuwgsfp3gpgwrtlwpft.png",
      provider: "cloudinary",
      provider_metadata: {
        public_id: "teuwgsfp3gpgwrtlwpft",
        resource_type: "image",
      },
      created_at: "2020-01-03T22:51:52.618Z",
      updated_at: "2020-01-03T22:51:52.618Z",
    },
  },
  {
    id: 16,
    title: "Sx 81 Computer",
    price: 949.99,
    description:
      "Tofu hoodie pop-up try-hard vice cornhole gluten-free keytar mlkshk 8-bit small batch four loko letterpress. Yr cornhole hoodie tote bag wayfarers mustache mumblecore crucifix hell of single-origin coffee pinterest. Readymade la croix activated charcoal cray edison bulb. Woke marfa helvetica hashtag green juice keffiyeh street art locavore four loko brunch flexitarian. Wayfarers fanny pack pork belly semiotics VHS affogato mixtape tumblr glossier jianbing freegan kinfolk pug. Intelligentsia pug 8-bit microdosing salvia locavore 90's umami gastropub iceland church-key marfa readymade 3 wolf moon keffiyeh. Tofu seitan mlkshk, try-hard cray hella PBR&B kale chips bushwick umami salvia knausgaard four loko pork belly semiotics.",
    featured: true,
    created_at: "2020-01-03T22:55:57.211Z",
    updated_at: "2020-01-03T23:01:53.227Z",
    category: "computer",
    free_shipping: true,
    extra_field: null,
    image: {
      id: 19,
      name: "product-9.png",
      hash: "22931d3c425f4d668318e6f3e4397a84",
      sha256: "uQFCztn_LA9Sw3W1xqd6Ari+OfxX8n3VEB4dA7O0dNE",
      ext: ".png",
      mime: "image/png",
      size: "357.51",
      url:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1578092157/w1gfnsqegqss7krnw6id.png",
      provider: "cloudinary",
      provider_metadata: {
        public_id: "w1gfnsqegqss7krnw6id",
        resource_type: "image",
      },
      created_at: "2020-01-03T22:55:57.699Z",
      updated_at: "2020-01-03T22:55:57.699Z",
    },
  },
  {
    id: 18,
    title: "Pure Radio",
    price: 45.99,
    description:
      "Tofu hoodie pop-up try-hard vice cornhole gluten-free keytar mlkshk 8-bit small batch four loko letterpress. Yr cornhole hoodie tote bag wayfarers mustache mumblecore crucifix hell of single-origin coffee pinterest. Readymade la croix activated charcoal cray edison bulb. Woke marfa helvetica hashtag green juice keffiyeh street art locavore four loko brunch flexitarian. Wayfarers fanny pack pork belly semiotics VHS affogato mixtape tumblr glossier jianbing freegan kinfolk pug. Intelligentsia pug 8-bit microdosing salvia locavore 90's umami gastropub iceland church-key marfa readymade 3 wolf moon keffiyeh. Tofu seitan mlkshk, try-hard cray hella PBR&B kale chips bushwick umami salvia knausgaard four loko pork belly semiotics.",
    featured: true,
    created_at: "2020-01-03T23:00:48.812Z",
    updated_at: "2020-01-03T23:00:48.812Z",
    category: "radio",
    free_shipping: true,
    extra_field: null,
    image: {
      id: 21,
      name: "product-11.png",
      hash: "0177cf8d190a4e2cb8765d94a4f0397a",
      sha256: "ZzTLbXKUN7PEoBJA-80Mzp3s277T-loEz4qmXcJNNmA",
      ext: ".png",
      mime: "image/png",
      size: "477.58",
      url:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1578092449/x1btyeyvdcibv6xtmow8.png",
      provider: "cloudinary",
      provider_metadata: {
        public_id: "x1btyeyvdcibv6xtmow8",
        resource_type: "image",
      },
      created_at: "2020-01-03T23:00:49.383Z",
      updated_at: "2020-01-03T23:00:49.383Z",
    },
  },
  {
    id: 13,
    title: "Atari Computer",
    price: 550.99,
    description:
      "Tofu hoodie pop-up try-hard vice cornhole gluten-free keytar mlkshk 8-bit small batch four loko letterpress. Yr cornhole hoodie tote bag wayfarers mustache mumblecore crucifix hell of single-origin coffee pinterest. Readymade la croix activated charcoal cray edison bulb. Woke marfa helvetica hashtag green juice keffiyeh street art locavore four loko brunch flexitarian. Wayfarers fanny pack pork belly semiotics VHS affogato mixtape tumblr glossier jianbing freegan kinfolk pug. Intelligentsia pug 8-bit microdosing salvia locavore 90's umami gastropub iceland church-key marfa readymade 3 wolf moon keffiyeh. Tofu seitan mlkshk, try-hard cray hella PBR&B kale chips bushwick umami salvia knausgaard four loko pork belly semiotics.",
    featured: false,
    created_at: "2020-01-03T22:50:00.243Z",
    updated_at: "2020-01-03T23:01:26.632Z",
    category: "computer",
    free_shipping: null,
    extra_field: null,
    image: {
      id: 16,
      name: "product-6.png",
      hash: "2bc718f610cd41a79e72446f8e6ec4f8",
      sha256: "PLgZ19-N_p+0-+vGeHi7a+yVoOu6-1E3AYzBhW6ipKw",
      ext: ".png",
      mime: "image/png",
      size: "404.53",
      url:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1578091800/wqvvkaukwdikbqfqlzy8.png",
      provider: "cloudinary",
      provider_metadata: {
        public_id: "wqvvkaukwdikbqfqlzy8",
        resource_type: "image",
      },
      created_at: "2020-01-03T22:50:00.796Z",
      updated_at: "2020-01-03T22:50:00.796Z",
    },
  },
  {
    id: 19,
    title: "Old School Radio",
    price: 89.99,
    description:
      "Tofu hoodie pop-up try-hard vice cornhole gluten-free keytar mlkshk 8-bit small batch four loko letterpress. Yr cornhole hoodie tote bag wayfarers mustache mumblecore crucifix hell of single-origin coffee pinterest. Readymade la croix activated charcoal cray edison bulb. Woke marfa helvetica hashtag green juice keffiyeh street art locavore four loko brunch flexitarian. Wayfarers fanny pack pork belly semiotics VHS affogato mixtape tumblr glossier jianbing freegan kinfolk pug. Intelligentsia pug 8-bit microdosing salvia locavore 90's umami gastropub iceland church-key marfa readymade 3 wolf moon keffiyeh. Tofu seitan mlkshk, try-hard cray hella PBR&B kale chips bushwick umami salvia knausgaard four loko pork belly semiotics.",
    featured: null,
    created_at: "2020-01-03T23:03:56.528Z",
    updated_at: "2020-01-03T23:03:56.528Z",
    category: "radio",
    free_shipping: true,
    extra_field: null,
    image: {
      id: 22,
      name: "product-12.png",
      hash: "533cab7404ce4c9ca1ce90f7c2ac7ac1",
      sha256: "k9TD66aPfQ2OX8XHKNyjgOqct1GNNz0ZBgVAKVuTsQ0",
      ext: ".png",
      mime: "image/png",
      size: "358.25",
      url:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1578092636/rnvhjpb6obisl85wubcp.png",
      provider: "cloudinary",
      provider_metadata: {
        public_id: "rnvhjpb6obisl85wubcp",
        resource_type: "image",
      },
      created_at: "2020-01-03T23:03:57.093Z",
      updated_at: "2020-01-03T23:03:57.093Z",
    },
  },
  {
    id: 20,
    title: "Retro Radio",
    price: 78.99,
    description:
      "Tofu hoodie pop-up try-hard vice cornhole gluten-free keytar mlkshk 8-bit small batch four loko letterpress. Yr cornhole hoodie tote bag wayfarers mustache mumblecore crucifix hell of single-origin coffee pinterest. Readymade la croix activated charcoal cray edison bulb. Woke marfa helvetica hashtag green juice keffiyeh street art locavore four loko brunch flexitarian. Wayfarers fanny pack pork belly semiotics VHS affogato mixtape tumblr glossier jianbing freegan kinfolk pug. Intelligentsia pug 8-bit microdosing salvia locavore 90's umami gastropub iceland church-key marfa readymade 3 wolf moon keffiyeh. Tofu seitan mlkshk, try-hard cray hella PBR&B kale chips bushwick umami salvia knausgaard four loko pork belly semiotics.",
    featured: null,
    created_at: "2020-01-03T23:05:44.733Z",
    updated_at: "2020-01-03T23:05:44.733Z",
    category: "radio",
    free_shipping: null,
    extra_field: null,
    image: {
      id: 23,
      name: "product-13.png",
      hash: "29ca2fed57cb4126843619f6314e5026",
      sha256: "2nf_IsTvg3jVAoh784F-kEhe7qolo8At4c7udFuAr9c",
      ext: ".png",
      mime: "image/png",
      size: "631.85",
      url:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1578092745/irvmkdrqqfun3fjnlllc.png",
      provider: "cloudinary",
      provider_metadata: {
        public_id: "irvmkdrqqfun3fjnlllc",
        resource_type: "image",
      },
      created_at: "2020-01-03T23:05:45.439Z",
      updated_at: "2020-01-03T23:05:45.439Z",
    },
  },
  {
    id: 21,
    title: "Bittium Radio",
    price: 60.99,
    description:
      "Tofu hoodie pop-up try-hard vice cornhole gluten-free keytar mlkshk 8-bit small batch four loko letterpress. Yr cornhole hoodie tote bag wayfarers mustache mumblecore crucifix hell of single-origin coffee pinterest. Readymade la croix activated charcoal cray edison bulb. Woke marfa helvetica hashtag green juice keffiyeh street art locavore four loko brunch flexitarian. Wayfarers fanny pack pork belly semiotics VHS affogato mixtape tumblr glossier jianbing freegan kinfolk pug. Intelligentsia pug 8-bit microdosing salvia locavore 90's umami gastropub iceland church-key marfa readymade 3 wolf moon keffiyeh. Tofu seitan mlkshk, try-hard cray hella PBR&B kale chips bushwick umami salvia knausgaard four loko pork belly semiotics.",
    featured: null,
    created_at: "2020-01-03T23:07:14.809Z",
    updated_at: "2020-01-03T23:07:14.809Z",
    category: "radio",
    free_shipping: true,
    extra_field: null,
    image: {
      id: 25,
      name: "product-14.png",
      hash: "312f877aa6104d09993eb6ad5af33678",
      sha256: "_xbJnwm9JVKT37+eimuuLB4BpNity0grw+WEPk1UHj8",
      ext: ".png",
      mime: "image/png",
      size: "548.63",
      url:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1578092894/vvwylnoygcijxmvfgome.png",
      provider: "cloudinary",
      provider_metadata: {
        public_id: "vvwylnoygcijxmvfgome",
        resource_type: "image",
      },
      created_at: "2020-01-03T23:08:14.339Z",
      updated_at: "2020-01-03T23:08:14.339Z",
    },
  },
  {
    id: 22,
    title: "Goodmans Radio",
    price: 120.99,
    description:
      "Tofu hoodie pop-up try-hard vice cornhole gluten-free keytar mlkshk 8-bit small batch four loko letterpress. Yr cornhole hoodie tote bag wayfarers mustache mumblecore crucifix hell of single-origin coffee pinterest. Readymade la croix activated charcoal cray edison bulb. Woke marfa helvetica hashtag green juice keffiyeh street art locavore four loko brunch flexitarian. Wayfarers fanny pack pork belly semiotics VHS affogato mixtape tumblr glossier jianbing freegan kinfolk pug. Intelligentsia pug 8-bit microdosing salvia locavore 90's umami gastropub iceland church-key marfa readymade 3 wolf moon keffiyeh. Tofu seitan mlkshk, try-hard cray hella PBR&B kale chips bushwick umami salvia knausgaard four loko pork belly semiotics.",
    featured: null,
    created_at: "2020-01-03T23:09:40.617Z",
    updated_at: "2020-01-03T23:09:40.617Z",
    category: "radio",
    free_shipping: null,
    extra_field: null,
    image: {
      id: 26,
      name: "product-15.png",
      hash: "8037c8fea54f490b8b945bb5182d4791",
      sha256: "q2aQwcV76c9RPcdm09pPGwVBBJn7IQKn33qbszEWP30",
      ext: ".png",
      mime: "image/png",
      size: "345.74",
      url:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1578092980/g7cmnntyzgl8g2siv5hg.png",
      provider: "cloudinary",
      provider_metadata: {
        public_id: "g7cmnntyzgl8g2siv5hg",
        resource_type: "image",
      },
      created_at: "2020-01-03T23:09:41.035Z",
      updated_at: "2020-01-03T23:09:41.035Z",
    },
  },
  {
    id: 17,
    title: "Mac Vintage ",
    price: 699.99,
    description:
      "Tofu hoodie pop-up try-hard vice cornhole gluten-free keytar mlkshk 8-bit small batch four loko letterpress. Yr cornhole hoodie tote bag wayfarers mustache mumblecore crucifix hell of single-origin coffee pinterest. Readymade la croix activated charcoal cray edison bulb. Woke marfa helvetica hashtag green juice keffiyeh street art locavore four loko brunch flexitarian. Wayfarers fanny pack pork belly semiotics VHS affogato mixtape tumblr glossier jianbing freegan kinfolk pug. Intelligentsia pug 8-bit microdosing salvia locavore 90's umami gastropub iceland church-key marfa readymade 3 wolf moon keffiyeh. Tofu seitan mlkshk, try-hard cray hella PBR&B kale chips bushwick umami salvia knausgaard four loko pork belly semiotics.",
    featured: null,
    created_at: "2020-01-03T22:58:48.131Z",
    updated_at: "2020-01-04T12:43:48.088Z",
    category: "computer",
    free_shipping: null,
    extra_field: null,
    image: {
      id: 20,
      name: "product-10.png",
      hash: "ad1e4805c669469d8e513ab6c020ecd8",
      sha256: "4qUl6ygABKljdq8Cu1qdMzN8F7uP6ZCUhNnBP5edjzw",
      ext: ".png",
      mime: "image/png",
      size: "414.01",
      url:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1578092328/lcgzbkwzdixmlarlqaa7.png",
      provider: "cloudinary",
      provider_metadata: {
        public_id: "lcgzbkwzdixmlarlqaa7",
        resource_type: "image",
      },
      created_at: "2020-01-03T22:58:48.594Z",
      updated_at: "2020-01-03T22:58:48.594Z",
    },
  },
];
